=== Saikarpe/WTL_Assignment/assignment2(XML,DTD)/catalog.dtd
<!ELEMENT university (university_name, address, department+, student+)>

<!ELEMENT university_name (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ELEMENT department (dept_name, faculty+, course+)>
<!ELEMENT dept_name (#PCDATA)>

<!ELEMENT faculty (faculty_name, designation, email)>
<!ELEMENT faculty_name (#PCDATA)>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT course (course_title, course_code, credits, semester)>
<!ELEMENT course_title (#PCDATA)>
<!ELEMENT course_code (#PCDATA)>
<!ELEMENT credits (#PCDATA)>
<!ELEMENT semester (#PCDATA)>

<!ELEMENT student (student_name, roll_no, department_name, enrolled_courses)>
<!ELEMENT student_name (#PCDATA)>
<!ELEMENT roll_no (#PCDATA)>
<!ELEMENT department_name (#PCDATA)>
<!ELEMENT enrolled_courses (#PCDATA)>

=== Saikarpe/WTL_Assignment/assignment2(XML,DTD)/catalog.xml
<!DOCTYPE university SYSTEM "catalog.dtd">

<university>

    <university_name>Sanjivani University</university_name>
    <address>Kopargaon</address>

    <department>
        <dept_name>Computer Science</dept_name>

        <faculty>
            <faculty_name>Dr. Brahmne Sir</faculty_name>
            <designation></designation>
            <email>sharma@abc.edu</email>
        </faculty>

        <faculty>
            <faculty_name>Ms. Patil</faculty_name>
            <designation>Assistant Professor</designation>
            <email>patil@abc.edu</email>
        </faculty>

        <course>
            <course_title>Data Structures</course_title>
            <course_code>CS101</course_code>
            <credits>4</credits>
            <semester>3</semester>
        </course>

        <course>
            <course_title>Algorithms</course_title>
            <course_code>CS102</course_code>
            <credits>4</credits>
            <semester>4</semester>
        </course>
    </department>

    <student>
        <student_name>Rahul Patil</student_name>
        <roll_no>1</roll_no>
        <department_name>Computer Science</department_name>
        <enrolled_courses>CS101, CS102</enrolled_courses>
    </student>

    <student>
        <student_name>Anita Desai</student_name>
        <roll_no>2</roll_no>
        <department_name>Computer Science</department_name>
        <enrolled_courses>CS102</enrolled_courses>
    </student>

</university>
